#include <MKL25Z4.h>

#define RED_LED1 7 // PortC Pin 7
#define RED_LED2 0 // PortC Pin 0
#define RED_LED3 3 // PortC Pin 3
#define RED_LED4 4 // PortC Pin 4
#define RED_LED5 5 // PortC Pin 5
#define RED_LED6 6 // PortC Pin 6
#define RED_LED7 10 // PortC Pin 10
#define RED_LED8 11 // PortC Pin 11
#define GREEN_LED1 30 // PortE Pin 30
#define GREEN_LED2 29 // PortE Pin 29
#define GREEN_LED3 23 // PortE Pin 23
#define GREEN_LED4 22 // PortE Pin 22
#define GREEN_LED5 21 // PortE Pin 21
#define GREEN_LED6 20 // PortE Pin 20
#define GREEN_LED7 5 // PortE Pin 5
#define GREEN_LED8 4 // PortE Pin 4


//enum color_t{RED,GREEN,BLUE};
void InitGPIO(void) {
		// Enable Clock to PORTB and PORTD
		SIM->SCGC5 |= ((SIM_SCGC5_PORTC_MASK) | (SIM_SCGC5_PORTE_MASK));
		// Configure MUX settings to make all 3 pins GPIO
		PORTC->PCR[RED_LED1] &= ~PORT_PCR_MUX_MASK;
		PORTC->PCR[RED_LED1] |= PORT_PCR_MUX(1);
		PORTC->PCR[RED_LED2] &= ~PORT_PCR_MUX_MASK;
		PORTC->PCR[RED_LED2] |= PORT_PCR_MUX(1);
		PORTC->PCR[RED_LED3] &= ~PORT_PCR_MUX_MASK;
		PORTC->PCR[RED_LED3] |= PORT_PCR_MUX(1);
		PORTC->PCR[RED_LED4] &= ~PORT_PCR_MUX_MASK;
		PORTC->PCR[RED_LED4] |= PORT_PCR_MUX(1);
		PORTC->PCR[RED_LED5] &= ~PORT_PCR_MUX_MASK;
		PORTC->PCR[RED_LED5] |= PORT_PCR_MUX(1);
		PORTC->PCR[RED_LED6] &= ~PORT_PCR_MUX_MASK;
		PORTC->PCR[RED_LED6] |= PORT_PCR_MUX(1);
		PORTC->PCR[RED_LED7] &= ~PORT_PCR_MUX_MASK;
		PORTC->PCR[RED_LED7] |= PORT_PCR_MUX(1);
		PORTC->PCR[RED_LED8] &= ~PORT_PCR_MUX_MASK;
		PORTC->PCR[RED_LED8] |= PORT_PCR_MUX(1);
		
		PORTE->PCR[GREEN_LED1] &= ~PORT_PCR_MUX_MASK;
		PORTE->PCR[GREEN_LED1] |= PORT_PCR_MUX(1);
		PORTE->PCR[GREEN_LED2] &= ~PORT_PCR_MUX_MASK;
		PORTE->PCR[GREEN_LED2] |= PORT_PCR_MUX(1);
		PORTE->PCR[GREEN_LED3] &= ~PORT_PCR_MUX_MASK;
		PORTE->PCR[GREEN_LED3] |= PORT_PCR_MUX(1);
		PORTE->PCR[GREEN_LED4] &= ~PORT_PCR_MUX_MASK;
		PORTE->PCR[GREEN_LED4] |= PORT_PCR_MUX(1);
		PORTE->PCR[GREEN_LED5] &= ~PORT_PCR_MUX_MASK;
		PORTE->PCR[GREEN_LED5] |= PORT_PCR_MUX(1);
		PORTE->PCR[GREEN_LED6] &= ~PORT_PCR_MUX_MASK;
		PORTE->PCR[GREEN_LED6] |= PORT_PCR_MUX(1);
		PORTE->PCR[GREEN_LED7] &= ~PORT_PCR_MUX_MASK;
		PORTE->PCR[GREEN_LED7] |= PORT_PCR_MUX(1);
		PORTE->PCR[GREEN_LED8] &= ~PORT_PCR_MUX_MASK;
		PORTE->PCR[GREEN_LED8] |= PORT_PCR_MUX(1);

		
		// Set Data Direction Registers for PortB and PortD
		PTE->PDDR |= (MASK(GREEN_LED1) | MASK(GREEN_LED2) | MASK(GREEN_LED3) |	MASK(GREEN_LED4) |
					MASK(GREEN_LED5) | MASK(GREEN_LED6) | MASK(GREEN_LED7) | MASK(GREEN_LED8) );
		PTC->PDDR |= (MASK(RED_LED1) | MASK(RED_LED2) | MASK(RED_LED3) |	MASK(RED_LED4) |
				MASK(RED_LED5) | MASK(RED_LED6) | MASK(RED_LED7) | MASK(RED_LED8) );
		PTE->PCOR |= (MASK(GREEN_LED1) | MASK(GREEN_LED2) | MASK(GREEN_LED3) |	MASK(GREEN_LED4) |
					MASK(GREEN_LED5) | MASK(GREEN_LED6) | MASK(GREEN_LED7) | MASK(GREEN_LED8) );
		PTC->PCOR |= (MASK(RED_LED1) | MASK(RED_LED2) | MASK(RED_LED3) |	MASK(RED_LED4) |
				MASK(RED_LED5) | MASK(RED_LED6) | MASK(RED_LED7) | MASK(RED_LED8) );			
}

void FlashTwice(void) {
	
	PTE->PDOR = (MASK(GREEN_LED1) | MASK(GREEN_LED2) | MASK(GREEN_LED3) |	MASK(GREEN_LED4) |
					MASK(GREEN_LED5) | MASK(GREEN_LED6) | MASK(GREEN_LED7) | MASK(GREEN_LED8) );
	osDelay(0x800000);
	PTE->PCOR = (MASK(GREEN_LED1) | MASK(GREEN_LED2) | MASK(GREEN_LED3) |	MASK(GREEN_LED4) |
					MASK(GREEN_LED5) | MASK(GREEN_LED6) | MASK(GREEN_LED7) | MASK(GREEN_LED8) );
	osDelay(0x800000);
}

void TurnAllGreenOn(void) {
	PTE->PDOR = (MASK(GREEN_LED1) | MASK(GREEN_LED2) | MASK(GREEN_LED3) |	MASK(GREEN_LED4) |
					MASK(GREEN_LED5) | MASK(GREEN_LED6) | MASK(GREEN_LED7) | MASK(GREEN_LED8) );
}

void SequenceGreen(void) {
	PTE->PDOR = MASK(GREEN_LED1);
	osDelay(0x800000);
	PTE->PDOR = MASK(GREEN_LED2);
	osDelay(0x800000);
	PTE->PDOR = MASK(GREEN_LED3);
	osDelay(0x800000);
	PTE->PDOR = MASK(GREEN_LED4);
	osDelay(0x800000);
	PTE->PDOR = MASK(GREEN_LED5);
	osDelay(0x800000);
	PTE->PDOR = MASK(GREEN_LED6);
	osDelay(0x800000);
	PTE->PDOR = MASK(GREEN_LED7);
	osDelay(0x800000);
	PTE->PDOR = MASK(GREEN_LED8);
	osDelay(0x800000);
}

void FlashRed500ms(void){
	PTC->PTOR |= (MASK(RED_LED1) | MASK(RED_LED2) | MASK(RED_LED3) |	MASK(RED_LED4) |
				MASK(RED_LED5) | MASK(RED_LED6) | MASK(RED_LED7) | MASK(RED_LED8) );
	osDelay(500000);				
}

void FlashRed250ms(void){
	PTC->PTOR |= (MASK(RED_LED1) | MASK(RED_LED2) | MASK(RED_LED3) |	MASK(RED_LED4) |
				MASK(RED_LED5) | MASK(RED_LED6) | MASK(RED_LED7) | MASK(RED_LED8) );
	osDelay(250000);				
}

/*
void controlLed(int mode) {
	switch(mode){
		case 1:
			
	}
}
*/





